package hospital.hospital.rules;
import hospital.hospital.model.cep.MessageEvent;
import hospital.hospital.services.MailService;
import hospital.hospital.model.cep.alarms.MessageAlarm;
global MailService mailService

rule "Blood Pressure new2"
	agenda-group "doctor-alarms"
    when
        $e : MessageEvent(message.getPatientId() == 2, $value1: message.getBloodPressureSystolic(), $value1 < 110.0, $value2: message.getBloodPressureDiastolic(), $value2 > 90.0)
    then
        insert(new MessageAlarm(2, "bloodPressure2", $value1, $value2));
        System.out.println("==== TRIGEROVAN ALARM ZA PREVISOK DONJI I PRENIZAK GORNJI PRITISAK za pacijenta ====");
end
rule "Message alarm triggered, notify doctor (blood pressure)2"
    when
        $alarm : MessageAlarm(variable == "bloodPressure2")
    then
        mailService.notifyDoctors($alarm);
end


