package hospital.hospital.rules;
import hospital.hospital.model.cep.LogEvent;
import hospital.hospital.services.MailService;
import hospital.hospital.model.cep.alarms.CustomLogAlarm;
import java.util.Date;
global MailService mailService

rule "feefwe_0"
    when
        $time :  Date()
        $previous: LogEvent(log.getType() in ("ERROR","LOGIN_ERROR","APPLICATION","LOGIN"))
        $l1 : LogEvent(
                log.getType() in ("APPLICATION"),
                log.getSeverity().name() in ("WARN","INFO","ERROR","TRACE"),
                this != $previous,
                this after[0, 10000] $previous
                )
        $appearance: Long(intValue >= 0) from accumulate(
                                    $l2: LogEvent(
                                        this != $l1,
                                        log.getType() in ("APPLICATION"),
                                        log.getSeverity().name() in ("WARN","INFO","ERROR","TRACE")
                                    )
                                    over window:time(60s),
                                    count($l2)
                                )
         $next: LogEvent(
                   log.getType() in ("ERROR","LOGIN_ERROR","APPLICATION","LOGIN"),
                   this != $l1,
                   this after[0, 10000] $l1
                   )
            not (CustomLogAlarm(date == $time))
    then
       System.out.println("\n\n==== TRIGEROVAN CUSTOM LOG ALARM  ===");
       System.out.println("RULE NAME: " + "feefwe");
       insert(new CustomLogAlarm($time, "wfwfwf"));
end
rule "Custom log alarm triggered, notify admin by email_feefwe_"
  when
        $alarm : CustomLogAlarm($message: errorMsg, $date: date)
    then
        System.out.println("Salje se mejl");
        String msg = "Custom log alarm triggered on date : " + $date + ". Alarm message: " + $message + ".";
        mailService.notifyAdmin($alarm.getAdminEmail(), msg);
end


