package hospital.hospital.rules;

import hospital.hospital.model.cep.MessageEvent;
import hospital.hospital.services.MailService;
import hospital.hospital.model.cep.alarms.MessageAlarm;

global MailService mailService


rule "High temperature."
	agenda-group "doctor-alarms"
    when
        $e : MessageEvent($patientId: message.getPatientId(), $value: message.getBodyTemperature(), $value > 40.0)
    then
        insert(new MessageAlarm($patientId, "bodyTemperature", $value));
        System.out.println("==== TRIGEROVAN ALARM ZA PREVISOKU TEMPERATURU ====");
end

rule "Message alarm triggered, notify doctor1"
    when
        $alarm : MessageAlarm(variable == "bodyTemperature")
    then
        mailService.notifyDoctors($alarm);
end


rule "High pulse rate."
	agenda-group "doctor-alarms"
    when
        $e : MessageEvent($patientId: message.getPatientId(), $value: message.getPulseRaye(), $value > 100.0)
    then
        insert(new MessageAlarm($patientId, "pulseRate", $value));
        System.out.println("==== TRIGEROVAN ALARM ZA PREVISOK PULS ====");
end

rule "Message alarm triggered, notify doctor2"
    when
        $alarm : MessageAlarm(variable == "pulseRate")
    then
        mailService.notifyDoctors($alarm);
end


rule "High respiration rate."
	agenda-group "doctor-alarms"
    when
        $e : MessageEvent($patientId: message.getPatientId(), $value: message.getRespirationRate(), $value > 17.0)
    then
        insert(new MessageAlarm($patientId, "respirationRate", $value));
        System.out.println("==== TRIGEROVAN ALARM ZA PREVISOK RESPIRATION RATE ====");
end

rule "Message alarm triggered, notify doctor3"
    when
        $alarm : MessageAlarm(variable == "respirationRate")
    then
        mailService.notifyDoctors($alarm);
end


rule "High systolic blood pressure."
	agenda-group "doctor-alarms"
    when
        $e : MessageEvent($patientId: message.getPatientId(), $value: message.getBloodPressureSystolic(), $value > 130.0)
    then
        insert(new MessageAlarm($patientId, "bloodPressureSystolic", $value));
        System.out.println("==== TRIGEROVAN ALARM ZA PREVISOK PRITISAK ====");
end

rule "Message alarm triggered, notify doctor4"
    when
        $alarm : MessageAlarm(variable == "bloodPressureSystolic")
    then
        mailService.notifyDoctors($alarm);
end


rule "Low systolic blood pressure, high diastolic blood pressure."
	agenda-group "doctor-alarms"
    when
        $e : MessageEvent($patientId: message.getPatientId(), $value1: message.getBloodPressureSystolic(), $value1 < 110.0, $value2: message.getBloodPressureDiastolic(), $value2 > 90.0)
    then
        insert(new MessageAlarm($patientId, "bloodPressure", $value1, $value2));
        System.out.println("==== TRIGEROVAN ALARM ZA PREVISOK DONJI I PRENIZAK GORNJI PRITISAK ====");
end

rule "Message alarm triggered, notify doctor5"
    when
        $alarm : MessageAlarm(variable == "bloodPressure")
    then
        mailService.notifyDoctors($alarm);
end
