package hospital.hospital.rules;

import hospital.hospital.model.cep.LogEvent;
import hospital.hospital.model.cep.UserLoginEvent;
import hospital.hospital.services.MailService;


import hospital.hospital.model.cep.alarms.InactiveUserAlarm;

import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

global MailService mailService

declare AlarmTriggered
    username: String
    attempts: Long
end

rule "More than 100 unsuccessful logins with same username in 60 sec, notify admin of hospital"
    when
          $l1: LogEvent($username: log.getUsername(), log.getType() == "LOGIN_ERROR")
                 $attempts: Long(intValue >= 100) from accumulate(
                            $l2: LogEvent(
                                this != $l1,
                                log.getUsername() == $username,
                                log.getType() == "LOGIN_ERROR",
                                this meets[60s] $l1
                            ),
                            count($l2)
                        )
                         not (AlarmTriggered(username == $username))
    then
        System.out.println("==== TRIGEROVAN ALARM ZA 100 POKUSAJA U MINUTI ===");
        System.out.println("username: " + $username);
        System.out.println($attempts);
        insert(new AlarmTriggered($username, $attempts));
end

rule "Alarm triggered, notify user by email"
    when
        AlarmTriggered($username: username, $attempts: attempts)
    then
       System.out.println("daa");
end

rule "User logged in after more than 90 days from last login, triger NotActiveAlarm"
    when
        $e : UserLoginEvent($email: email, $lastLogin: lastLogin)
        eval(ChronoUnit.DAYS.between($lastLogin, LocalDate.now()) >= 90)
    then
        insert(new InactiveUserAlarm($email, ChronoUnit.DAYS.between($lastLogin, LocalDate.now())));
        System.out.println("==== TRIGEROVAN ALARM ZA NEAKTIVNOG KORISNIKA ====");
        System.out.println("username: " + $email);
end

rule "Inactive user alarm triggered, notify admin by email"
  when
        $alarm : InactiveUserAlarm($userEmail: userEmail, $daysInactive: daysInactive)
    then
        String msg = "User with email : " + $userEmail + " hasn't been active for more than 90 days and tried to log in today.";
        mailService.notifyAdmin($alarm.getAdminEmail(), msg);
end