export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const AUTH_USER = 'AUTH_USER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const RESET_MESSAGE = 'RESET_MESSAGE';

export const GET_REQUESTS = 'GET_REQUESTS';
export const SET_REQUESTS = 'SET_REQUESTS';
export const ADD_REQUEST = 'ADD_REQUEST';

export const ADD_DOCTOR = 'ADD_DOCTOR';

export const GET_LOGS = 'GET_LOGS';
export const SET_LOGS = 'SET_LOGS';

export const GET_ALARMS_BLACKLISTED = 'GET_ALARMS_BLACKLISTED';
export const SET_ALARMS_BLACKLISTED = 'SET_ALARMS_BLACKLISTED';
export const GET_ALARMS_BRUTEFORCE = 'GET_ALARMS_BRUTEFORCE';
export const SET_ALARMS_BRUTEFORCE = 'SET_ALARMS_BRUTEFORCE';
export const GET_ALARMS_ERROR = 'GET_ALARMS_ERROR';
export const SET_ALARMS_ERROR = 'SET_ALARMS_ERROR';
export const GET_ALARMS_INACTIVE = 'GET_ALARMS_INACTIVE';
export const SET_ALARMS_INACTIVE = 'SET_ALARMS_INACTIVE';

export const GET_MESSAGES = 'GET_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';

export const GET_MESSAGE_ALARMS = 'GET_MESSAGE_ALARMS';
export const SET_MESSAGE_ALARMS = 'SET_MESSAGE_ALARMS';

export const GET_PATIENTS = 'GET_PATIENTS';
export const SET_PATIENTS = 'SET_PATIENTS';

export const ADD_TEMPERATURE_RULE = 'ADD_TEMPERATURE_RULE';
export const ADD_PRESSURE_RULE = 'ADD_PRESSURE_RULE';
export const ADD_CUSTOM_MESSAGE_RULE = 'ADD_CUSTOM_MESSAGE_RULE';

export const GENERATE_REPORT = 'GENERATE_REPORT';
export const SET_REPORT = 'SET_REPORT';

export const GET_REPORTS = 'GET_REPORTS';
export const SET_REPORTS = 'SET_REPORTS';
