package hospital.hospital.rules;
import hospital.hospital.model.cep.LogEvent;
import hospital.hospital.services.MailService;
import hospital.hospital.model.cep.alarms.CustomLogAlarm;
import java.util.Date;
global MailService mailService

rule "OVOVOV_0"
no-loop true
    when
      $l1 : LogEvent(
                    log.getType() in ("LOGIN_ERROR"),
                    log.getSeverity().name() in ("ERROR","TRACE","INFO")
                    )
            $appearance: Long(intValue >= 2) from accumulate(
                                        $l2: LogEvent(
                                            this != $l1,
                                            log.getType() in ("LOGIN_ERROR"),
                                            log.getSeverity().name() in ("ERROR","TRACE","INFO")
                                        )
                                        over window:time(20s),
                                        count($l2)
                                    )
            not (CustomLogAlarm(ruleName == "OVOVOV"))
    then
       System.out.println("\n\n==== TRIGEROVAN CUSTOM LOG ALARM  ===");
       System.out.println("RULE NAME: " + "OVOVOV");
       insert(new CustomLogAlarm($l1.getLog().getTimestamp(), "aaddwaadwd", "OVOVOV"));
end
rule "Custom log alarm triggered, notify admin by email_OVOVOV_"
no-loop true
  when
        $alarm : CustomLogAlarm($message: errorMsg, $date: date, sentEmail == false)
    then
        System.out.println("\n\nSENDING EMAIL...");
        String msg = "Custom log alarm triggered on date : " + $date + ". Alarm message: " + $message + ". Rule name: " + $alarm.getRuleName();
        mailService.notifyAdmin($alarm.getAdminEmail(), msg);
          mailService.saveCustomAlarm($alarm);
         modify($alarm) { setSentEmail(true); }
end


